# -*- coding: utf-8 -*-
"""2GBQ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ml7402LUJuDohyeHcpPFZTgETElmFThu
"""

import numpy as np
import pandas as pd
from sqlalchemy import create_engine
import pymysql
import pyodbc
from google.oauth2 import service_account
from google.cloud import bigquery
import smtplib
from datetime import datetime
import logging
import requests
import time

#create GCP Client
client = bigquery.Client.from_service_account_json('F:/voltaic-country-280607-ea3eb5348029.json')

headers = {
    'authorization': 'Bearer VBxdGeTLbdcPs1M',
    'content-type': 'application/json'
}

logs = []

netsuite_query = '''
    SELECT
        CAST(TRANSACTIONS.TRANDATE AS date) AS TRANDATE,
        TRANSACTIONS.TRANID,
        TRANSACTIONS.CUSTOMER_PHONE,
        TRANSACTION_LINES.LOCATION_ID,
        - SUM(TRANSACTION_LINES.ITEM_COUNT) AS 'ITEM_COUNT',
        - SUM(TRANSACTION_LINES.NET_AMOUNT) AS 'NET_AMOUNT'
    FROM
        "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTION_LINES TRANSACTION_LINES
        LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".TRANSACTIONS TRANSACTIONS ON TRANSACTION_LINES.TRANSACTION_ID = TRANSACTIONS.TRANSACTION_ID
        LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".INVENTORY_ITEMS ON TRANSACTION_LINES.ITEM_ID = INVENTORY_ITEMS.ITEM_ID
        LEFT JOIN "Vua Nem Joint Stock Company"."Vua Nem - Storehouse Officer".SERVICE_ITEMS ON SERVICE_ITEMS.ITEM_ID = TRANSACTION_LINES.ITEM_ID
    WHERE
        TRANSACTION_LINES.ACCOUNT_ID IN (480, 482, 487, 498, 505, 508, 509, 510, 511, 54, 1079, 1170)
        AND TRANSACTIONS.TRANSACTION_TYPE IN ('Sales Order')
        AND TRANSACTIONS.STATUS <> 'Closed'
        AND (
                (INVENTORY_ITEMS.DISPLAYNAME IS NOT NULL)
                OR(SERVICE_ITEMS.ITEM_ID IN ('136263', '136264'))
        )
    GROUP BY
        TRANSACTIONS.TRANDATE,
        TRANSACTIONS.CREATE_DATE,
        TRANSACTIONS.TRANID,
        TRANSACTION_LINES.LOCATION_ID,
        TRANSACTIONS.CUSTOMER_PHONE
        '''

#get NetSuite from query
def get_netsuite(query):
    cnxn = pyodbc.connect('DSN=NetSuiteML;uid=minh.le@vuanem.com;PWD=BI@2023cute')
    sales_order = pd.read_sql(query, cnxn)
    print(sales_order.head())
    return sales_order

sales_order = get_netsuite(netsuite_query)

netsuite_schema = [
    bigquery.SchemaField("TRANDATE", "DATE"),
    bigquery.SchemaField('TRANID', "STRING"),
    bigquery.SchemaField('CUSTOMER_PHONE', "STRING"),
    bigquery.SchemaField("LOCATION_ID", "FLOAT"),
    bigquery.SchemaField('ITEM_COUNT', "FLOAT"),
    bigquery.SchemaField("NET_AMOUNT", "FLOAT")]

def load_gbq(df, table_id, schema):
    job_config = bigquery.LoadJobConfig(
        schema=schema,
        write_disposition = 'WRITE_TRUNCATE',
        parquet_compression='snappy',
        source_format= 'PARQUET')
    #    time_partitioning = bigquery.TimePartitioning(
    #        type_ = bigquery.TimePartitioningType.DAY,
    #        field = partition_field))
    print(f'Loading to `{table_id}`...')
    job = client.load_table_from_dataframe(
        df, table_id, job_config=job_config)
    print('Sleep for 5 sec...')
    time.sleep(5)
    table = client.get_table(table_id)  # Make an API request.
    print(job.result())
    result = "Loaded {} rows and {} columns to {}".format(table.num_rows, len(table.schema), table_id)
    print(result)
    logs.append(result)

load_gbq(df=sales_order,
         table_id='NetSuite.SalesOrder',
         schema=netsuite_schema)

del sales_order

caresoft_tickets_query = '''
SELECT
    cst.care_soft_ticket_id,
    cst.ticket_no,
    cst.ticket_subject,
    cst.ticket_status,
    cst.ticket_source,
    cst.ticket_priority,
    cst.assignee_id,
    cst.requester_id,
    cst.requester_name,
    cst.requester_email,
    cst.requester_phone_no,
    cst.sla,
    cst.campaign_name,
    cst.created_at,
    cst.updated_at
FROM
    vuanem_ecommerce.care_soft_tickets cst
'''

sql_specs = {
    'username': 'root',
    'pwd': 'VuaNem@2020',
    'server': '1.55.215.47',
    'db_name': 'vuanem_ecommerce'
}

def get_caresoft_tickets(query):
    sqlEngine = create_engine(r'mysql+pymysql://{0}:{1}@{2}/{3}'.format(sql_specs['username'], sql_specs['pwd'], sql_specs['server'], sql_specs['db_name']))
    dbConnection = sqlEngine.connect()
    caresoft_tickets = pd.read_sql(query, dbConnection)
    print(caresoft_tickets.head())
    return caresoft_tickets

caresoft_tickets = get_caresoft_tickets(caresoft_tickets_query)

caresoft_tickets.to_excel('caresoft_tickets.xlsx', index=False)

caresoft_tickets_schema = [
    bigquery.SchemaField('care_soft_ticket_id', "INTEGER"),
    bigquery.SchemaField('ticket_no', "INTEGER"),
    bigquery.SchemaField("ticket_subject", "STRING"),
    bigquery.SchemaField('ticket_status', "STRING"),
    bigquery.SchemaField("ticket_source", "STRING"),
    bigquery.SchemaField('ticket_priority', "STRING"),
    bigquery.SchemaField('assignee_id', "INTEGER"),
    bigquery.SchemaField('requester_id', "INTEGER"),
    bigquery.SchemaField('requester_name', "STRING"),
    bigquery.SchemaField('requester_email', "STRING"),
    bigquery.SchemaField('requester_phone_no', "STRING"),
    bigquery.SchemaField('sla', "STRING"),
    bigquery.SchemaField('campaign_name', "STRING"),
    bigquery.SchemaField('created_at', "TIMESTAMP"),
    bigquery.SchemaField('updated_at', "TIMESTAMP")]

load_gbq(
    df=caresoft_tickets,
    table_id='Caresoft.caresoft_tickets',
    schema=caresoft_tickets_schema
)

caresoft_tickets_custom_fields_query = '''
SELECT
	ticket_id,
	SUM(CASE WHEN custom_filed_id = 4871 THEN custom_filed_value ELSE null END) AS trang_thai_cham_soc,
	SUM(CASE WHEN custom_filed_id = 4893 THEN custom_filed_value ELSE null END) AS trang_thai_tiep_nhan
FROM
	vuanem_ecommerce.care_soft_ticket_custom_fileds cstcf
GROUP BY ticket_id
'''

caresoft_tickets_custom_fields = get_caresoft_tickets(caresoft_tickets_custom_fields_query)

r2 = requests.get('https://api.caresoft.vn/VUANEM/api/v1/tickets/custom_fields', headers=headers).json()
care_status_df = pd.DataFrame(r2['custom_fields'][0])
care_status_df = pd.json_normalize(care_status_df.to_dict('list'), ['values']).apply(pd.Series)
receive_status_df = pd.DataFrame(r2['custom_fields'][1])
receive_status_df = pd.json_normalize(receive_status_df.to_dict('list'), ['values']).apply(pd.Series)

def transform_tickets_custom_fields(df):
    df = df.merge(care_status_df, how='left', left_on='trang_thai_cham_soc', right_on='id')
    df = df.merge(receive_status_df, how='left', left_on='trang_thai_tiep_nhan', right_on='id')
    df = df.drop(['trang_thai_cham_soc', 'trang_thai_tiep_nhan', 'id_x', 'id_y'], axis=1)
    df.rename(mapper={
        'lable_x': 'trang_thai_cham_soc',
        'lable_y': 'trang_thai_tiep_nhan'
    }, axis=1, inplace=True)
    return df

caresoft_tickets_custom_fields = transform_tickets_custom_fields(caresoft_tickets_custom_fields)

caresoft_tickets_custom_fields_schema = [
    bigquery.SchemaField('ticket_id', "INTEGER"),
    bigquery.SchemaField('trang_thai_cham_soc', "STRING"),
    bigquery.SchemaField("trang_thai_tiep_nhan", "STRING")]

load_gbq(
    df=caresoft_tickets_custom_fields,
    table_id='Caresoft.caresoft_tickets_custom_fields',
    schema=caresoft_tickets_custom_fields_schema
)

del caresoft_tickets, caresoft_tickets_custom_fields

caresoft_call_logs_query = '''
SELECT
    call_id,
    care_soft_id,
    customer_id,
    caller,
    agent_id,
    group_id,
    call_type,
    call_status,
    start_time,
    end_time,
    created_at,
    updated_at
FROM
    vuanem_ecommerce.care_soft_call_logs cscl
'''

caresoft_call_logs = get_caresoft_tickets(caresoft_call_logs_query)

caresoft_call_logs_schema = [
    bigquery.SchemaField('call_id', "STRING"),
    bigquery.SchemaField('care_soft_id', "INTEGER"),
    bigquery.SchemaField("customer_id", "INTEGER"),
    bigquery.SchemaField('caller', "STRING"),
    bigquery.SchemaField("agent_id", "INTEGER"),
    bigquery.SchemaField('group_id', "INTEGER"),
    bigquery.SchemaField('call_type', "INTEGER"),
    bigquery.SchemaField('call_status', "STRING"),
    bigquery.SchemaField('start_time', "TIMESTAMP"),
    bigquery.SchemaField('end_time', "TIMESTAMP"),
    bigquery.SchemaField('created_at', "TIMESTAMP"),
    bigquery.SchemaField('updated_at', "TIMESTAMP")]

load_gbq(
    df=caresoft_call_logs,
    table_id='Caresoft.caresoft_call_logs',
    schema=caresoft_call_logs_schema
)

client.close()

logging.basicConfig(filename='2GBQ.log', level=logging.INFO)
logging.info(datetime.now().strftime('%Y-%m-%dT%H:%M:%S'))
logging.info('\n'.join(logs))